// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Bare `dotenv/config` only loads `.env`. We also load `.env.local` — where
// `vercel env pull` writes DATABASE_URL by default, and what Next.js itself
// already prioritizes — without overriding a real env var already set by
// Vercel's own build environment (dotenv never overwrites an existing value
// unless told to).
import { config } from "dotenv";
config({ path: ".env.local" });
config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
